awk -v replace_start=95 -v replace_end=118 '
NR < replace_start { print }
NR == replace_start {
    print "    override suspend fun loadDetails(url: String): CineHubMediaDetails? = withContext(Dispatchers.IO) {"
    print "        try {"
    print "            val clean = url.removePrefix(\"ext://$id/\")"
    print "            val isTv = clean.startsWith(\"tv/\")"
    print "            val tmdbId = clean.removePrefix(\"tv/\").removePrefix(\"movie/\").substringBefore(\"?\")"
    print "            if (isTv) {"
    print "                val details = CineOnlineScraper.fetchTvShowDetails(tmdbId) ?: return@withContext null"
    print "                val episodes = mutableListOf<CineHubEpisode>()"
    print "                details.seasons.forEach { season ->"
    print "                    if (season.season_number > 0) {"
    print "                        val eps = CineOnlineScraper.fetchTvShowEpisodes(null, tmdbId, season.season_number, details.name)"
    print "                        eps.forEach { ep ->"
    print "                            episodes.add(CineHubEpisode("
    print "                                id = \"${url}_S${ep.season}E${ep.episode}\","
    print "                                name = ep.title,"
    print "                                season = ep.season,"
    print "                                episode = ep.episode,"
    print "                                data = \"tv:${tmdbId}:${ep.season}:${ep.episode}\","
    print "                                posterUrl = ep.stillPath"
    print "                            ))"
    print "                        }"
    print "                    }"
    print "                }"
    print "                CineHubMediaDetails("
    print "                    id = url, title = details.name ?: \"\", url = url, providerId = id, providerName = name,"
    print "                    posterUrl = details.poster_path?.let { \"https://image.tmdb.org/t/p/w500$it\" }, backdropUrl = details.backdrop_path?.let { \"https://image.tmdb.org/t/p/w500$it\" }, overview = details.overview,"
    print "                    year = details.first_air_date?.take(4)?.toIntOrNull(), rating = details.vote_average,"
    print "                    genres = emptyList(), cast = emptyList(),"
    print "                    type = TvType.TvSeries, episodes = episodes"
    print "                )"
    print "            } else {"
    print "                val movie = CineOnlineScraper.getOrFetchMovie(null, \"\", tmdbId) ?: return@withContext null"
    print "                CineHubMediaDetails("
    print "                    id = url, title = movie.title, url = url, providerId = id, providerName = name,"
    print "                    posterUrl = movie.posterPath, backdropUrl = movie.backdropPath, overview = movie.plot,"
    print "                    year = movie.premiered.take(4).toIntOrNull(), rating = movie.userRating,"
    print "                    genres = listOfNotNull(movie.genre.ifBlank { null }), cast = movie.actors.map { it.name },"
    print "                    type = TvType.Movie"
    print "                )"
    print "            }"
    print "        } catch (e: Exception) { null }"
    print "    }"
}
NR > replace_end { print }
' app/src/main/kotlin/xyz/mpv/rex/cinehub/extension/providers/DeclarativeCineHubProvider.kt > temp.kt && mv temp.kt app/src/main/kotlin/xyz/mpv/rex/cinehub/extension/providers/DeclarativeCineHubProvider.kt
