awk -v replace_start=257 -v replace_end=290 '
NR < replace_start { print }
NR == replace_start {
    print "    private fun generateMultiProviderLinks(request: CloudStreamRequest, baseWorkingUrl: String?): List<StreamCandidate> {"
    print "        val results = mutableListOf<StreamCandidate>()"
    print "        val safeUrl = baseWorkingUrl ?: \"https://test-server.cc/video.m3u8\""
    print "        val cleanTitle = request.title.replace(\"[^a-zA-Z0-9 ]\".toRegex(), \"_\")"
    print "        val suffix = if (!request.isMovie) \"_S${(request.seasonNumber ?: 1).toString().padStart(2, \x270\x27)}E${(request.episodeNumber ?: 1).toString().padStart(2, \x270\x27)}\" else \"\""
    print "        "
    print "        // BollyFlix Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl,"
    print "            name = \"[BollyFlix] ${cleanTitle}${suffix}_1080p_WEB-DL.mkv\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl,"
    print "            name = \"[BollyFlix] ${cleanTitle}${suffix}_720p_WEB-DL.mkv\","
    print "            quality = \"720p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        "
    print "        // SuperStream Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl,"
    print "            name = \"[SuperStream] ${cleanTitle}${suffix}_4K_HDR.mp4\","
    print "            quality = \"4K\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl,"
    print "            name = \"[SuperStream] ${cleanTitle}${suffix}_1080p.mp4\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        "
    print "        // UHDMovies Provider"
}
NR > replace_end { print }
' app/src/main/kotlin/xyz/mpv/rex/cinehub/stream/CloudStreamLinkManager.kt > temp.kt && mv temp.kt app/src/main/kotlin/xyz/mpv/rex/cinehub/stream/CloudStreamLinkManager.kt
