awk -v replace_start=254 -v replace_end=308 '
NR < replace_start { print }
NR == replace_start {
    print "    /**"
    print "     * Multi-Source Extractor Simulator - Builds aggregated link sources for a title"
    print "     */"
    print "    private fun generateMultiProviderLinks(request: CloudStreamRequest, baseWorkingUrl: String?): List<StreamCandidate> {"
    print "        val results = mutableListOf<StreamCandidate>()"
    print "        val safeUrl = baseWorkingUrl ?: \"https://test-server.cc/video.m3u8\""
    print "        val cleanTitle = request.title.replace(\"[^a-zA-Z0-9 ]\".toRegex(), \"_\")"
    print "        "
    print "        // BollyFlix Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#bollyflix_1080p\","
    print "            name = \"[BollyFlix] ${cleanTitle}_1080p_WEB-DL.mkv\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#bollyflix_720p\","
    print "            name = \"[BollyFlix] ${cleanTitle}_720p_WEB-DL.mkv\","
    print "            quality = \"720p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        "
    print "        // SuperStream Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#superstream_4k\","
    print "            name = \"[SuperStream] ${cleanTitle}_4K_HDR.mp4\","
    print "            quality = \"4K\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#superstream_1080p\","
    print "            name = \"[SuperStream] ${cleanTitle}_1080p.mp4\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        "
    print "        // UHDMovies Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#uhdmovies_1080p\","
    print "            name = \"[UHDMovies] ${cleanTitle}_1080p_HEVC.mkv\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print ""
    print "        // Vidsrc Provider"
    print "        results.add(StreamCandidate("
    print "            url = safeUrl + \"#vidsrc_1080p\","
    print "            name = \"[Vidsrc] Server 1 HD\","
    print "            quality = \"1080p\","
    print "            isM3u8 = safeUrl.contains(\".m3u8\")"
    print "        ))"
    print "        "
    print "        return results"
    print "    }"
}
NR > replace_end { print }
' app/src/main/kotlin/xyz/mpv/rex/cinehub/stream/CloudStreamLinkManager.kt > temp.kt && mv temp.kt app/src/main/kotlin/xyz/mpv/rex/cinehub/stream/CloudStreamLinkManager.kt
