awk -v replace_start=49 -v replace_end=74 '
NR < replace_start { print }
NR == replace_start {
    print "    override suspend fun loadDetails(url: String): CineHubMediaDetails? = withContext(Dispatchers.IO) {"
    print "        val isTv = url.contains(\"tmdb://tv/\")"
    print "        val idStr = url.removePrefix(\"tmdb://tv/\").removePrefix(\"tmdb://movie/\")"
    print "        if (isTv) {"
    print "            val details = CineOnlineScraper.fetchTvShowDetails(idStr) ?: return@withContext null"
    print "            val episodes = mutableListOf<CineHubEpisode>()"
    print "            details.seasons.forEach { season ->"
    print "                if (season.season_number > 0) {"
    print "                    val eps = CineOnlineScraper.fetchTvShowEpisodes(context, idStr, season.season_number, details.name)"
    print "                    eps.forEach { ep ->"
    print "                        episodes.add(CineHubEpisode("
    print "                            id = \"${url}_S${ep.season}E${ep.episode}\", name = ep.title,"
    print "                            season = ep.season, episode = ep.episode, data = \"tv:${idStr}:${ep.season}:${ep.episode}\","
    print "                            posterUrl = ep.stillPath"
    print "                        ))"
    print "                    }"
    print "                }"
    print "            }"
    print "            CineHubMediaDetails("
    print "                id = idStr, title = details.name ?: \"\", url = url, providerId = id, providerName = name,"
    print "                posterUrl = details.poster_path?.let { \"https://image.tmdb.org/t/p/w500$it\" }, backdropUrl = details.backdrop_path?.let { \"https://image.tmdb.org/t/p/w500$it\" }, overview = details.overview,"
    print "                year = details.first_air_date?.take(4)?.toIntOrNull(), rating = details.vote_average, genres = emptyList(),"
    print "                cast = emptyList(), type = TvType.TvSeries, episodes = episodes"
    print "            )"
    print "        } else {"
    print "            val movie = CineOnlineScraper.getOrFetchMovie(context, \"\", idStr) ?: return@withContext null"
    print "            CineHubMediaDetails("
    print "                id = movie.tmdbId, title = movie.title, url = url, providerId = id, providerName = name,"
    print "                posterUrl = movie.posterPath, backdropUrl = movie.backdropPath, overview = movie.plot,"
    print "                year = movie.premiered.take(4).toIntOrNull(), rating = movie.userRating, genres = listOfNotNull(movie.genre.ifBlank { null }),"
    print "                cast = movie.actors.map { it.name }, type = TvType.Movie"
    print "            )"
    print "        }"
    print "    }"
}
NR > replace_end { print }
' app/src/main/kotlin/xyz/mpv/rex/cinehub/extension/providers/CineOnlineBridgeProvider.kt > temp.kt && mv temp.kt app/src/main/kotlin/xyz/mpv/rex/cinehub/extension/providers/CineOnlineBridgeProvider.kt
