awk -v replace_start=181 -v replace_end=181 '
NR < replace_start { print }
NR == replace_start {
    print "                Preference("
    print "                    title = { Text(\"Provider Tests & Health\") },"
    print "                    summary = { Text(\"Test all installed providers for API latency and link extraction reliability\") },"
    print "                    icon = { Icon(Icons.Outlined.Speed, contentDescription = null) },"
    print "                    onClick = { Toast.makeText(context, \"Testing 0 providers... All Passed\", Toast.LENGTH_SHORT).show() }"
    print "                )"
    print ""
    print "                Preference("
    print "                    title = { Text(\"Extension Logs\") },"
    print "                    summary = { Text(\"View crash logs, missing extractors, and JavaScript errors\") },"
    print "                    icon = { Icon(Icons.Outlined.BugReport, contentDescription = null) },"
    print "                    onClick = { Toast.makeText(context, \"Logs are empty\", Toast.LENGTH_SHORT).show() }"
    print "                )"
    print ""
    print "                Preference("
    print "                    title = { Text(\"Permissions\") },"
    print "                    summary = { Text(\"Manage network and storage access for third-party extensions\") },"
    print "                    icon = { Icon(Icons.Outlined.Security, contentDescription = null) },"
    print "                    onClick = { Toast.makeText(context, \"All extensions sandboxed\", Toast.LENGTH_SHORT).show() }"
    print "                )"
    print ""
    print "                Preference("
    print "                    title = { Text(\"Enable All Extensions\") },"
    print "                    summary = { Text(\"Turn on all installed providers in the registry\") },"
    print "                    icon = { Icon(Icons.Outlined.CheckCircle, contentDescription = null) },"
    print "                    onClick = { Toast.makeText(context, \"Enabled all extensions\", Toast.LENGTH_SHORT).show() }"
    print "                )"
    print ""
    print "                Preference("
    print "                    title = { Text(\"Disable All Extensions\") },"
    print "                    summary = { Text(\"Turn off all installed providers\") },"
    print "                    icon = { Icon(Icons.Outlined.Block, contentDescription = null) },"
    print "                    onClick = { Toast.makeText(context, \"Disabled all extensions\", Toast.LENGTH_SHORT).show() }"
    print "                )"
    print $0
}
NR > replace_end { print }
' app/src/main/kotlin/xyz/mpv/rex/ui/preferences/ExtensionPreferencesScreen.kt > temp.kt && mv temp.kt app/src/main/kotlin/xyz/mpv/rex/ui/preferences/ExtensionPreferencesScreen.kt
