package xyz.mpv.rex.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

val controlColor = Color(0xFFFFFFFF)

// ============================================================================
// Official MAX STREAM Brand Palette
// ============================================================================
val MaxStreamRed = Color(0xFFFF2A3D)
val MaxStreamBlue = Color(0xFF2563FF)
val MaxStreamCyan = Color(0xFF38E8FF)
val MaxStreamPurple = Color(0xFF8B5CF6)
val MaxStreamPink = Color(0xFFFF3EC9)
val MaxStreamOrange = Color(0xFFFF2A3D)

val MaxStreamBgDark = Color(0xFF000000)
val MaxStreamSurfaceDark = Color(0xFF0B0B0B)
val MaxStreamSurfaceElevated = Color(0xFF111111)
val MaxStreamSurfaceHigh = Color(0xFF1A1A1A)

val MaxStreamTextPrimary = Color(0xFFFFFFFF)
val MaxStreamTextSecondary = Color(0xFFB3B3B3)
val MaxStreamTextTertiary = Color(0xFF7A7A7A)

// Signature multi-color brand gradient
val MaxStreamGradient = listOf(
  Color(0xFFFF2A3D),
  Color(0xFFFF3EC9),
  Color(0xFF8B5CF6),
  Color(0xFF2563FF),
  Color(0xFF38E8FF),
)

val MaxStreamHorizontalGradientBrush = Brush.horizontalGradient(MaxStreamGradient)
val MaxStreamLinearGradientBrush = Brush.linearGradient(MaxStreamGradient)

// ============================================================================
// Light Color Scheme Tokens
// ============================================================================
val primaryLight = Color(0xFFFF3B30)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE5E3)
val onPrimaryContainerLight = Color(0xFF8B0E07)
val secondaryLight = Color(0xFF007AFF)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E8FF)
val onSecondaryContainerLight = Color(0xFF003882)
val tertiaryLight = Color(0xFFA855F7)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF3E5FF)
val onTertiaryContainerLight = Color(0xFF4A0E80)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBFBFC)
val onBackgroundLight = Color(0xFF121214)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF121214)
val surfaceVariantLight = Color(0xFFF0F1F5)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF75777F)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1A1A1A)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFFF6B62)
val surfaceDimLight = Color(0xFFE4E4E8)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F7FA)
val surfaceContainerLight = Color(0xFFF0F0F5)
val surfaceContainerHighLight = Color(0xFFE8E8EE)
val surfaceContainerHighestLight = Color(0xFFE0E0E7)

val primaryLightMediumContrast = Color(0xFFD3180F)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFFF5E54)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF0056B3)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF3395FF)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF7E22CE)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFBF7AF9)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFBFBFC)
val onBackgroundLightMediumContrast = Color(0xFF121214)
val surfaceLightMediumContrast = Color(0xFFFFFFFF)
val onSurfaceLightMediumContrast = Color(0xFF0F1116)
val surfaceVariantLightMediumContrast = Color(0xFFF0F1F5)
val onSurfaceVariantLightMediumContrast = Color(0xFF33363E)
val outlineLightMediumContrast = Color(0xFF50525A)
val outlineVariantLightMediumContrast = Color(0xFF6A6D75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF1A1A1A)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFFF6B62)
val surfaceDimLightMediumContrast = Color(0xFFC6C6CD)
val surfaceBrightLightMediumContrast = Color(0xFFFBFBFC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7F7FA)
val surfaceContainerLightMediumContrast = Color(0xFFE8E8EE)
val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

val primaryLightHighContrast = Color(0xFF8B0E07)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFFD3180F)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF003882)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF0056B3)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4A0E80)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF7E22CE)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFBFBFC)
val onBackgroundLightHighContrast = Color(0xFF121214)
val surfaceLightHighContrast = Color(0xFFFFFFFF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF0F1F5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292C33)
val outlineVariantLightHighContrast = Color(0xFF464951)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF1A1A1A)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFF6B62)
val surfaceDimLightHighContrast = Color(0xFFB8B8BF)
val surfaceBrightLightHighContrast = Color(0xFFFBFBFC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4DB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6CD)

// ============================================================================
// Dark Color Scheme Tokens (Cinematic Premium Dark OTT: #08090C & #101218)
// ============================================================================
val primaryDark = Color(0xFFFF2A4D)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF8B0E23)
val onPrimaryContainerDark = Color(0xFFFFD9DF)
val secondaryDark = Color(0xFF00D2FF)
val onSecondaryDark = Color(0xFF003543)
val secondaryContainerDark = Color(0xFF004E63)
val onSecondaryContainerDark = Color(0xFFBBEFFF)
val tertiaryDark = Color(0xFFA855F7)
val onTertiaryDark = Color(0xFF380860)
val tertiaryContainerDark = Color(0xFF5B178D)
val onTertiaryContainerDark = Color(0xFFF3E8FF)
val errorDark = Color(0xFFFF6B6B)
val onErrorDark = Color(0xFF5C000B)
val errorContainerDark = Color(0xFF8C0015)
val onErrorContainerDark = Color(0xFFFFDAD9)
val backgroundDark = Color(0xFF08090C)
val onBackgroundDark = Color(0xFFF5F6F8)
val surfaceDark = Color(0xFF101218)
val onSurfaceDark = Color(0xFFF5F6F8)
val surfaceVariantDark = Color(0xFF171B24)
val onSurfaceVariantDark = Color(0xFFA2A9B8)
val outlineDark = Color(0xFF282F3E)
val outlineVariantDark = Color(0xFF1D222D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0F2F6)
val inverseOnSurfaceDark = Color(0xFF0E1015)
val inversePrimaryDark = Color(0xFFFF2A4D)
val surfaceDimDark = Color(0xFF0B0D12)
val surfaceBrightDark = Color(0xFF252B3A)
val surfaceContainerLowestDark = Color(0xFF050608)
val surfaceContainerLowDark = Color(0xFF0D0F14)
val surfaceContainerDark = Color(0xFF13161F)
val surfaceContainerHighDark = Color(0xFF1B202C)
val surfaceContainerHighestDark = Color(0xFF242A38)

val primaryDarkMediumContrast = Color(0xFFFF7B73)
val onPrimaryDarkMediumContrast = Color(0xFF330200)
val primaryContainerDarkMediumContrast = Color(0xFFC4251B)
val onPrimaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val secondaryDarkMediumContrast = Color(0xFF67E8F9)
val onSecondaryDarkMediumContrast = Color(0xFF002933)
val secondaryContainerDarkMediumContrast = Color(0xFF00839E)
val onSecondaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val tertiaryDarkMediumContrast = Color(0xFFD8B4FE)
val onTertiaryDarkMediumContrast = Color(0xFF2E0450)
val tertiaryContainerDarkMediumContrast = Color(0xFF9333EA)
val onTertiaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF050505)
val onBackgroundDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceDarkMediumContrast = Color(0xFF101010)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF1A1A1A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE5E5E5)
val outlineDarkMediumContrast = Color(0xFF5A5A5E)
val outlineVariantDarkMediumContrast = Color(0xFF3A3A3E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0F0F0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF101010)
val inversePrimaryDarkMediumContrast = Color(0xFFFF3B30)
val surfaceDimDarkMediumContrast = Color(0xFF0A0A0A)
val surfaceBrightDarkMediumContrast = Color(0xFF2C2C2E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF000000)
val surfaceContainerLowDarkMediumContrast = Color(0xFF0D0D0D)
val surfaceContainerDarkMediumContrast = Color(0xFF18181A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF222224)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF2E2E32)

val primaryDarkHighContrast = Color(0xFFFFD5D2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFF7B73)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFE0F7FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF67E8F9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF3E8FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD8B4FE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF050505)
val onBackgroundDarkHighContrast = Color(0xFFFFFFFF)
val surfaceDarkHighContrast = Color(0xFF101010)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF1A1A1A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE5E5E7)
val outlineVariantDarkHighContrast = Color(0xFFB0B0B4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFFFF3B30)
val surfaceDimDarkHighContrast = Color(0xFF0A0A0A)
val surfaceBrightDarkHighContrast = Color(0xFF3A3A3C)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF101010)
val surfaceContainerDarkHighContrast = Color(0xFF1C1C1E)
val surfaceContainerHighDarkHighContrast = Color(0xFF2C2C2E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3A3A3C)

// ============================================================================
// Pure Black (AMOLED) Scheme
// ============================================================================
val primaryPureBlack = Color(0xFFFF453A)
val onPrimaryPureBlack = Color(0xFF4D0500)
val primaryContainerPureBlack = Color(0xFF8B0E07)
val onPrimaryContainerPureBlack = Color(0xFFFFDAD6)
val secondaryPureBlack = Color(0xFF32D7FF)
val onSecondaryPureBlack = Color(0xFF003642)
val secondaryContainerPureBlack = Color(0xFF004E5F)
val onSecondaryContainerPureBlack = Color(0xFFBBE9FF)
val tertiaryPureBlack = Color(0xFFC084FC)
val onTertiaryPureBlack = Color(0xFF3B0764)
val tertiaryContainerPureBlack = Color(0xFF581C87)
val onTertiaryContainerPureBlack = Color(0xFFF3E8FF)
val errorPureBlack = Color(0xFFFFB4AB)
val onErrorPureBlack = Color(0xFF690005)
val errorContainerPureBlack = Color(0xFF93000A)
val onErrorContainerPureBlack = Color(0xFFFFDAD6)
val backgroundPureBlack = Color(0xFF000000)
val onBackgroundPureBlack = Color(0xFFFFFFFF)
val surfacePureBlack = Color(0xFF000000)
val onSurfacePureBlack = Color(0xFFFFFFFF)
val surfaceVariantPureBlack = Color(0xFF141414)
val onSurfaceVariantPureBlack = Color(0xFFB3B3B3)
val outlinePureBlack = Color(0xFF282828)
val outlineVariantPureBlack = Color(0xFF1E1E1E)
val scrimPureBlack = Color(0xFF000000)
val inverseSurfacePureBlack = Color(0xFFFFFFFF)
val inverseOnSurfacePureBlack = Color(0xFF000000)
val inversePrimaryPureBlack = Color(0xFFFF3B30)
val surfaceDimPureBlack = Color(0xFF000000)
val surfaceBrightPureBlack = Color(0xFF1A1A1A)
val surfaceContainerLowestPureBlack = Color(0xFF000000)
val surfaceContainerLowPureBlack = Color(0xFF050505)
val surfaceContainerPureBlack = Color(0xFF0D0D0D)
val surfaceContainerHighPureBlack = Color(0xFF151515)
val surfaceContainerHighestPureBlack = Color(0xFF1F1F1F)
