name: CI/CD Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate short SHA
        id: set-short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        # Passing debug keystore properties ensures the release APK is signed and can be installed
        run: ./gradlew assembleRelease -PreleaseKeyStore=../debug.keystore -PreleaseKeyStorePassword=android -PreleaseKeyAlias=androiddebugkey -PreleaseKeyPassword=android

      - name: Upload app-arm64-v8a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvRex-arm64-v8a-release-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload app-armeabi-v7a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvRex-armeabi-v7a-release-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload app-universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvRex-universal-release-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-universal-release.apk

      - name: Upload app-x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvRex-x86-release-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload app-x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvRex-x86_64-release-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk